// constants/actionTypes.js
export const GET_MOVIE_INFO_REQUEST = "MOVIE_INFO/GET_MOVIE_INFO_REQUEST";
export const GET_MOVIE_INFO_SUCCESS = "MOVIE_INFO/GET_MOVIE_INFO_SUCCESS";
export const GET_MOVIE_INFO_FAILURE = "MOVIE_INFO/GET_MOVIE_INFO_FAILURE";